apiVersion: v1
data:
  ke-limit.yaml: |
    apiVersion: v1
    kind: LimitRange
    metadata:
      name: ke-limit
    spec:
      limits:
      - max:
          cpu: "4"
          memory: 8Gi
        min:
          cpu: 100m
          memory: 64Mi
        type: Pod
      - default:
          cpu: "1"
          memory: 2Gi
        defaultRequest:
          cpu: 100m
          memory: 512Mi
        max:
          cpu: "2"
          memory: 4Gi
        min:
          cpu: 100m
          memory: 64Mi
        type: Container
      - max:
          storage: 50Gi
        min:
          storage: 128Mi
        type: PersistentVolumeClaim
kind: ConfigMap
metadata:
  name: ke-limit
  namespace: kube-system
