apiVersion: v1
data:
  ke-quota.yaml: |
    apiVersion: v1
    kind: ResourceQuota
    metadata:
      name: ke-quota
    spec:
      hard:
        configmaps: "500"
        limits.cpu: 5k
        limits.memory: 5000Gi
        persistentvolumeclaims: 5k
        pods: "500"
        requests.cpu: 2k
        requests.memory: 2000Gi
        requests.storage: 10000Gi
        secrets: 5k
        services: "100"
        services.nodeports: "5"
kind: ConfigMap
metadata:
  name: ke-quota
  namespace: kube-system
