apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels:
    k8s-app: ns-initializer
  name: ns-initializer
  namespace: kube-system
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      k8s-app: ns-initializer
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        k8s-app: ns-initializer
    spec:
      containers:
      - command:
        - /usr/bin/ns-initializer
        - --logtostderr
        - --v=3
        - --quota=/etc/ns-initializer/quota/ke-quota.yaml
        - --limit=/etc/ns-initializer/limit/ke-limit.yaml
        image: hub.c.163.com/weiwei04/ns-initializer:0.1.0
        imagePullPolicy: IfNotPresent
        name: ns-initializer
        volumeMounts:
        - mountPath: /etc/ns-initializer/quota
          name: quota
        - mountPath: /etc/ns-initializer/limit
          name: limit
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      volumes:
      - configMap:
          name: ke-quota
        name: quota
      - configMap:
          name: ke-limit
        name: limit
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
